baseURL = 'https://aayush2492.github.io/ncc-iith-website/'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'NCC website'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "About"
  url= "about/"
  weight = 1
  [[menu.Main]]
  name = "Gallery"
  url= "gallery/"
  weight = 2
  # [[menu.Main]]
  # name = "Enrollment"
  # url= "/enrollment/"
  # weight = 3
  [[menu.Main]]
  name = "Contact"
  url= "contact/"
  weight = 4

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://nss.iith.ac.in\" target=\"_blank\">NCC </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.jpeg"
  footerlogo = "images/logo.jpeg"
  footerDescription = "For more Info please visit the official NCC website at indiancc.nic.in to learn more about NCC."

  [params.address]
  address = "IIT Hyderabad, Kandi, Telangana"
  email = "office.ncc@iith.ac.in"
  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  openingHours = "We are open from 7am — 7pm week days."
  phone = ""

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
